### ISSUE TITLE
Error: 14 UNAVAILABLE: failed to connect to all addresses

### ISSUE THREAD

**Issue by pparonson** [wbobeirne/lightning-app-tutorial#40]
I am trying to connect to a raspiblitz node. I'm getting the "Error: 14 UNAVAILABLE: failed to connect to all addresses" in the terminal console and "api.ts:55 WebSocket connection to 'ws://localhost:3001/api/posts' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED" in the browser console. Any help appreciated. Thanks.

**Comment by JamesTsetsekas** [comment]
I had the same issue! is your node running in umbrel by chance? if so there is a known issue preventing lnd grpc from working
https://github.com/getumbrel/umbrel/issues/1421

I got it working by opening a ssh shell with 10009 forwarded
For example on windows ssh -L 10009:localhost:10009 umbrel@umbrel.local

**Comment by pparonson** [comment]
@JamesTsetsekas  Thanks for your response!  I was running raspiblitz at the time. I think I still have the project and I will give your suggestion a try.
