### ISSUE TITLE
EventEmitter addListener() 

### ISSUE THREAD

**Issue by Janaka-Steph** [wbobeirne/lightning-app-tutorial#5]
Hello,

I would appreciate some help understanding your code here https://github.com/wbobeirne/lightning-app-tutorial/blob/master/server/index.ts#L35

```
const postListener = (post: any) => {
    ws.send(JSON.stringify({
      type: 'post',
      data: post,
    }));
  };
  postsManager.addListener('post', postListener);
```

This code above in ws route is executed every time a client connects to the server. 
The problem is that addListener() will register as many listeners.
> https://nodejs.org/api/events.html#events_emitter_on_eventname_listener
`Multiple calls passing the same combination of eventName and listener will result in the listener being added, and called, multiple times.`

Then when a 'post' event will be emitted, the EventEmitter will call the listener that many times.

I am wrong? If yes, why is it not the case?

Thank you

**Comment by wbobeirne** [comment]
Hey there, happy to answer. This will add a listener once per each websocket. When the websocket disconnects, we clean up after our listener ([here](https://github.com/wbobeirne/lightning-app-tutorial/blob/master/server/index.ts#L42-L46)). So each websocket connection (of which there can be many) will get sent each new post once and only once.

Hope that helps, let me know if you have any other questions.

**Comment by Janaka-Steph** [comment]
I don't get how postsManager can differentiate/segregate between websocket connections.

**Comment by wbobeirne** [comment]
It doesn't have to, it gets passed different `postListener` callback functions that have different references to `ws` instances. It's pretty similar to doing something like:

```ts
const numbers = [1, 2, 3, 4, 5]
numbers.map(num => {
  const postListener = () => console.log('New post for listener #' + num)
  postsManager.addListener("post", postListener)
})
```
In this case, `postsManager` doesn't need to differentiate between `num`, since all it has is that `postListener` function. And a new `postListener` is made for each number in `numbers`.
