### ISSUE TITLE
Fetch API + React not working

### ISSUE THREAD

**Issue by tiotolstoy** [wbobeirne/lightning-app-tutorial#8]
I'm using your project as inspiration for the Strike Hackathon. 

When I use `new Headers()` and append to it; it still comes out as an empty object on the other side.

I just realized I do not have node-fetch installed so I will install. I don't see where you are calling it however. How does this part of the code work?

**Comment by wbobeirne** [comment]
Hey, that's awesome to hear you're using this for the hackathon! There's no need for `node-fetch` as that bit of code runs in the user's browser, and `node-fetch` is only needed for running on the server side (in node.)

The `Headers` class isn't the same as a basic Javascript object, so if you print it out it won't list all of its attributes the same way if you did
```js
const headers = {};
headers['Accept'] = 'application/json';
```

If you want to inspect the headers, you'll want to run `headers.get('property')` for the properties you want to check out. Try the following code in your console's browser to check it out:

```js
const headers = new Headers();
headers.append('Accept', 'application/json');
console.log(headers.get('Accept'));
```
